version: '3.6'

services:
  api:
    image: node:12-alpine
    container_name: cpep-node
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - NODE_PORT=3000
      - ELASTIC_URL=http://elasticsearch:9200
    volumes:
      - .:/usr/src/app/cpep
    working_dir: /usr/src/app/cpep
    command: yarn start
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - esnet
  elasticsearch:
    container_name: cpep-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
volumes:
  esdata:
networks:
  esnet:

